eg_v2_cyclic = """
User input: what environment do cyclic steps indicate?
Answer: 
Hypothesis 1: Cyclic steps indicate a shallow marine environment characterized by strong tidal currents and wave action. This hypothesis is based on the observation that cyclic steps are commonly found in coastal areas with high energy environments, where the combination of tides and waves can create cyclic patterns in sediment deposition.
Based on the related papers, there is strong evidence supporting Hypothesis 1. The paper "Experiments on Wedge-Shaped Deep Sea Sedimentary Deposits in Minibasins and/or on Channel Levees Emplaced by Turbidity Currents. Part I. Documentation of the Flow" (DOI: 10.2110/JSR.2009.064) discusses the appearance of sediment waves identified as cyclic steps created by turbidity currents. It further mentions that cyclic steps can occur in bedrock or alluvial rivers as well as on the floor of the deep sea. Another paper, "Slootman Cartigny 2020 Cyclic steps" (DOI: Slootman_Cartigny_2020_Cyclic_steps), highlights the importance of cyclic steps in enhancing sediment transport efficiency and their role in the initiation and maintenance of fluvial and submarine channels. These findings provide strong support for Hypothesis 1.
Hypothesis 2: Cyclic steps indicate a fluvial environment with periodic fluctuations in water discharge. This hypothesis suggests that cyclic steps are formed by the interaction between a river and its floodplain, where variations in water flow result in the deposition of sediment in a repetitive pattern.
The related papers provide some evidence supporting Hypothesis 2. The paper "Morphodynamics of supercritical flow in a linked river and delta system, Daihai Lake, Northern China" (DOI: 10.1111/SED.12839) suggests that high sediment flux and substantial suspended sediment load of floods in a single active channel can favor the generation of cyclic steps. It also mentions the role of cyclic steps in enhancing sediment transport efficiency and their importance in the initiation and maintenance of river morphology. However, there is less direct evidence specifically linking cyclic steps to periodic fluctuations in water discharge. Therefore, Hypothesis 2 is supported to a lesser extent compared to Hypothesis 1.
Hypothesis 3: Cyclic steps indicate a deep-water environment influenced by turbidity currents. This hypothesis proposes that cyclic steps are formed by the downslope movement of sediment-laden currents, known as turbidity currents, which create cyclic patterns of sediment deposition in submarine canyons or deep-sea basins.
The related papers provide moderate support for Hypothesis 3. The paper "Morphodynamics and sedimentary structures of bedforms under supercritical‐flow conditions: New insights from flume experiments" (DOI: 10.1111/SED.12076) discusses the formation of cyclic steps by turbidity currents in submarine environments. Another paper, "Experiments on Wedge-Shaped Deep Sea Sedimentary Deposits in Minibasins and/or on Channel Levees Emplaced by Turbidity Currents. Part II. Morphodynamic Evolution of the Wedge and of the Associated Bedforms" (DOI: 10.2110/JSR.2009.065), provides a preliminary description of bedforms associated with supercritical turbidity currents, including cyclic steps. While there is evidence supporting the influence of turbidity currents on the formation of cyclic steps, the direct link between cyclic steps and deep-water environments influenced by turbidity currents is not as well-established as in Hypothesis 1.
Probability of each hypothesis:
Hypothesis 1: Highly likely
Hypothesis 3: Moderately likely
Hypothesis 2: Less likely
"""

eg_v3_zongshan_formation = """
Explanation of Process:
The Zongshan Formation's subdivision into members with distinct lithological units indicates a complex depositional history. The presence of thick-bedded micritic limestones at the base suggests deposition in a relatively calm, possibly deeper marine environment where fine carbonate mud could settle and lithify into limestone. The transition to calcareous shales and marls in the upper part of the Lower Member suggests an increase in siliciclastic input or a change in water energy levels, which could be associated with a shallowing upward sequence or a shift in the sediment supply.
The diverse and abundant foraminiferal assemblages, particularly planktonic taxa, suggest open marine conditions with sufficient depth to support such organisms. The presence of specific foraminifer zones indicates that the area experienced a range of oceanographic conditions over time, which can be correlated with global sea level and climatic changes.
The Upper Member, with its packstone layers intercalated with marls and calcareous shale, indicates a dynamic environment with episodes of higher energy conditions sufficient to rework sediments into packstones, which are grain-supported carbonate rocks that often form in somewhat more energetic water conditions than micrites.

List of Possible Environments:
The environments listed are ranked based on the probability of observing the described lithologies and fossil assemblages:
| Environment        | Probability | Documented Example                                           | References                                                   |
| ------------------ | ----------- | ------------------------------------------------------------ | ------------------------------------------------------------ |
| Deep Marine Shelf  | High        | Similar foraminiferal assemblages in the modern deep marine settings. | Title: Factors controlling the evolution of a wedge-top temperate-type carbonate platform in the Miocene of the northern Apennines (Italy); DOI: https://doi.org/10.1016/j.sedgeo.2015.01.007 |
| Slope and Basin    | Medium      | Ancient deepwater formations with similar micritic limestones and foraminifera. | Title: Litho- and biostratigraphy of the early Eocenelarger benthic foraminifera-dominated carbonates of the central Tethys domain, Zagros Foreland Basin, SW Iran; DOI: https://doi.org/10.1016/j.sedgeo.2023.106477 |
| Carbonate Platform | Medium      | Carbonate platforms known to contain similar thick-bedded limestones and fossil assemblages. | Title: Recognition and interpretation of depositional units in a late Neogene progradational shelf margin complex, Taranaki Basin, New Zealand: foraminiferal data compared with seismic facies and wireline logs; DOI: https://doi.org/10.1016/j.sedgeo.2003.09.002 |
| Reef Complex       | Low         | Although capable of supporting diverse faunal assemblages, typically exhibits more in-situ framework construction than seen in the described units. | Title: Factors controlling the evolution of a wedge-top temperate-type carbonate platform in the Miocene of the northern Apennines (Italy); DOI: https://doi.org/10.1016/j.sedgeo.2015.01.007 |"""

egs = [eg_v3_zongshan_formation]
